-- Create a table to store connected network devices
CREATE TABLE IF NOT EXISTS connected_devices (
    id bigint generated by default as identity primary key,
    ip_address text NOT NULL,
    mac_address text NOT NULL UNIQUE,
    vendor text,
    status text DEFAULT 'Online',
    last_seen timestamptz DEFAULT now(),
    created_at timestamptz DEFAULT now()
);

-- Create an index on IP address for faster lookups
CREATE INDEX IF NOT EXISTS idx_devices_ip ON connected_devices(ip_address);

-- Optional: Enable Row Level Security (RLS) if you want to restrict access
-- ALTER TABLE connected_devices ENABLE ROW LEVEL SECURITY;

-- Optional: Policy to allow read access to authenticated users
-- BOOLEAN policies would need to be created based on your specific auth setup
