-- Enable UUID extension if not enabled
create extension if not exists "uuid-ossp";

-- DEVICES TABLE
-- Stores the latest state of every discovered device
create table if not exists devices (
    id uuid primary key default uuid_generate_v4(),
    mac_address text unique not null,
    ip_address text,
    hostname text,
    vendor text,
    device_type text,         -- 'Laptop', 'Phone', 'Printer', 'Router', 'IoT', 'Server', 'Unknown'
    os_family text,          -- 'Windows', 'Linux', 'Android', 'iOS', 'MacOS', 'Embedded'
    os_version text,
    risk_level text default 'Low', -- 'Low', 'Medium', 'High', 'Critical'
    protocols_detected jsonb default '[]'::jsonb, -- List of protocols found e.g. ["ssh", "http", "snmp"]
    first_seen timestamp with time zone default now(),
    last_seen timestamp with time zone default now(),
    custom_name text,         -- User assigned name
    is_trusted boolean default false
);

-- DISCOVERY LOGS TABLE
-- Keeps a history of when devices were seen and how (Audit Trail)
create table if not exists discovery_logs (
    id bigint generated by default as identity primary key,
    device_id uuid references devices(id) on delete cascade,
    discovery_method text,    -- 'ARP', 'mDNS', 'SNMP', 'Active Scan'
    raw_data jsonb,           -- Any raw data captured during discovery
    timestamp timestamp with time zone default now()
);

-- PORT SCAN RESULTS (Optional linking to devices, or keep separate)
-- We can add a foreign key to the existing scan_results if needed, or just link by IP/MAC.
-- For now, let's leave existing scan_results as is, but maybe add mac_address to it if missing.

-- INDEXES
create index if not exists idx_devices_ip on devices(ip_address);
create index if not exists idx_devices_last_seen on devices(last_seen);
